# Generated by Django 4.0.4 on 2022-06-23 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tlg_id', models.CharField(db_index=True, max_length=50, verbose_name='ID телеграма пользователя')),
                ('user_tlg_name', models.CharField(max_length=100, verbose_name='Никнейм в телеграме')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя клиента')),
                ('last_shipping_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес доставки')),
                ('orders_numb', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество заказов')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'Пользователи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Название категории товаров')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
                'db_table': 'Категории товаров',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание товара')),
                ('price', models.FloatField(max_length=10, verbose_name='Цена товара')),
                ('number_of_items', models.IntegerField(verbose_name='Количество товара в наличии')),
                ('image_for_items_id', models.TextField(blank=True, max_length=2000, null=True, verbose_name='ID картинки для товара')),
                ('items_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_api.categories', verbose_name='Категория товаров')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'Товары',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='OrderBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_number_in_basket', models.IntegerField(default=1, verbose_name='Количество данного товара в корзине')),
                ('items_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_api.items', verbose_name='ID товара')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_api.botusers', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Товары в корзине',
                'verbose_name_plural': 'Товары в корзине',
                'db_table': 'Товары в корзине',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id_before_receiving', models.IntegerField(verbose_name='ID заказа перед получением клиентом')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заказа')),
                ('pay_status', models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Статус оплаты')),
                ('execution_status', models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Статус выполнения заказа')),
                ('order_items', models.TextField(max_length=4000, verbose_name='Товары из заказа')),
                ('result_orders_price', models.FloatField(verbose_name='Итоговая цена заказа')),
                ('need_milling', models.BooleanField(default=False, verbose_name='Помол')),
                ('shipping', models.BooleanField(default=False, verbose_name='Доставка')),
                ('shipping_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес доставки')),
                ('contact_telephone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_api.botusers', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Архив заказа',
                'verbose_name_plural': 'Архив заказов',
                'db_table': 'Архив заказов',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заказа')),
                ('pay_status', models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Статус оплаты')),
                ('execution_status', models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Статус выполнения заказа')),
                ('order_items', models.TextField(max_length=4000, verbose_name='Товары из заказа')),
                ('result_orders_price', models.FloatField(verbose_name='Итоговая цена заказа')),
                ('need_milling', models.BooleanField(default=False, verbose_name='Помол')),
                ('shipping', models.BooleanField(default=False, verbose_name='Доставка')),
                ('shipping_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес доставки')),
                ('contact_telephone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_api.botusers', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'Заказы',
                'ordering': ['-datetime'],
            },
        ),
    ]
