# Generated by Django 4.0.4 on 2022-06-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0002_alter_items_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['items_name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='botusers',
            name='user_tlg_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Никнейм в телеграме'),
        ),
    ]
