# Generated by Django 4.0.4 on 2022-06-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0003_alter_items_options_alter_botusers_user_tlg_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusers',
            name='orders_numb',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество заказов'),
        ),
    ]
