# Generated by Django 4.0.4 on 2022-06-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0004_alter_botusers_orders_numb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_api.botusers', verbose_name='Пользователь'),
        ),
    ]
